sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 22.0
  - 21.3
  - 21.2.3
  - 21.1
  - 21.0
  - 20.0
  - 19.0
matrix:
  include:
  - otp_release: 18.3
    dist: trusty
  - otp_release: 17.5
    dist: trusty
  - otp_release: R16B03-1
    dist: trusty
  - otp_release: R15B03
    dist: trusty
