sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 21.2.3
  - 21.1
  - 21.0
  - 20.0
  - 19.0
  - 18.3
  - 17.5
  - R16B03-1
  - R15B03
before_script:
  - kerl list installations
